{% set name = "emu" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: 'https://gitlab.com/treangenlab/emu/-/archive/v{{version}}/emu-v{{version}}.tar.gz'
  sha256: 4f76abd9a34480ee9dcea40e47b35317731f9f24fc57cb94aed1ca0b87b144ea


build:
  noarch: generic
  number: 0
  script: mkdir -p ${PREFIX}/bin && cp emu ${PREFIX}/bin

requirements:
  run:
    - biopython
    - python >=3
    - pysam >=0.15.3
    - numpy >=1.19.2
    - pandas >=1.1.3
    - flatten-dict >=0.3.0

test:
  source_files:
    - example
    - example/*
  commands:
    - emu --help 

about:
  home: https://gitlab.com/treangenlab/emu
  license: MIT
  license_file: LICENSE
  summary: Emu is a relative abundance estimator for 16s genomic data.
